# Site settings
title: Globetrotter 
email: victorouse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Globetrotter is a postgraduate project conducted at the University of Queensland, Australia. 
    The aim of this project is to design a context aware video retrieval system for tourists.
baseurl: "/globetrotter-docs" # the subpath of your site, e.g. /blog/
url: "http://victorouse.github.io/globetrotter-docs" # the base hostname & protocol for your site
github_username: victorouse 

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: :compressed
